baseURL = 'https://ai-workshop-newsletter.pages.dev/'
languageCode = 'en-us'
title = 'ai-workshop-newsletter'
theme = 'ananke'

enableEmoji = true
# Pagination settings
paginate = 10  # Set the number of posts per page

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  weight = 10
  url = "/posts/"

[[menu.main]]
  identifier = "tutorials"
  name = "Tutorials"
  weight = 20
  url = "/tutorials/"
  
# Sort order for posts (newest first)
[params]
  #[permalinks]
    #posts = "/:year/:month/:day/:slug/"
  [params.contact]
    email = 'info@example.org'

[frontmatter]
  date = ["date", ":default"]
  lastmod = ["lastmod", ":default"]
  draft = ["draft", ":default"]
  publishdate = ["publishdate", ":default"]
  expiryDate = ["expiryDate", ":default"]
  weight = ["weight", ":default"]
  aliases = ["aliases", ":default"]
  slug = ["slug", ":filename"]


  
 
 